services:

  backend:
    image: laxmanrayala08/ekart-backend:v1
    container_name: ekart-backend
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: on-failure

  frontend:
    image: laxmanrayala08/ekart-frontend:v1
    container_name: ekart-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend